base.url=https://demoqa.com
browser=chrome
headless=false
env=local
explicit.wait.sec=15
page.load.timeout.sec=45
script.timeout.sec=20

# Uncomment for Docker Selenium Grid: docker compose up -d
# grid.url=http://localhost:4444/wd/hub
